version: '3.8'

services:
  web:
    build: .
    container_name: health_organizer_app
    command: python main.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=True
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
