"""
Clinical Pharmacology & Drug Interactions: Oncology, Hematology & Respiratory Pharmacotherapy.
"""
from typing import Dict, List
from apps.clinical.models_interactions import (
    InteractionSeverity, EvidenceLevel, CYPEnzyme,
    DrugInteractionRecord, DrugMonograph
)

MONOGRAPHS_ONCOLOGY: Dict[str, DrugMonograph] = {
    "methotrexate": DrugMonograph(
        name="Methotrexate",
        pharmacological_class="Antimetabolite",
        summary_description="Dihydrofolate reductase inhibitor for severe active rheumatoid arthritis and oncology.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "cyclosporine": DrugMonograph(
        name="Cyclosporine",
        pharmacological_class="Calcineurin Inhibitor",
        summary_description="Immunosuppressive agent preventing IL-2 transcription in organ transplantation.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "tacrolimus": DrugMonograph(
        name="Tacrolimus",
        pharmacological_class="Calcineurin Inhibitor",
        summary_description="Macrolide immunosuppressive agent for allograft rejection prophylaxis in solid organ transplants.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "azathioprine": DrugMonograph(
        name="Azathioprine",
        pharmacological_class="Purine Antimetabolite",
        summary_description="Prodrug of 6-mercaptopurine inhibiting purine nucleotide synthesis for autoimmune disorders.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "montelukast": DrugMonograph(
        name="Montelukast",
        pharmacological_class="Leukotriene Receptor Antagonist",
        summary_description="CysLT1 receptor antagonist for chronic asthma maintenance and allergic rhinitis.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "salbutamol": DrugMonograph(
        name="Salbutamol",
        pharmacological_class="Short-Acting Beta-2 Agonist",
        summary_description="Rapid bronchodilator for acute bronchospasm and exercise-induced asthma prophylaxis.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "fluticasone": DrugMonograph(
        name="Fluticasone",
        pharmacological_class="Inhaled Corticosteroid",
        summary_description="Synthetic fluorinated glucocorticoid with minimal systemic bioavailability for persistent asthma.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
    "budesonide": DrugMonograph(
        name="Budesonide",
        pharmacological_class="Inhaled Corticosteroid",
        summary_description="Anti-inflammatory corticosteroid with high first-pass hepatic metabolism for asthma and COPD.",
        primary_indications=["Standard clinical guideline indication."],
        contraindications=["Hypersensitivity to active pharmaceutical ingredient."],
        black_box_warnings=["Requires therapeutic clinical monitoring."],
        standard_dosage_adult="Titrated standard clinical maintenance dosing.",
        renal_adjustment_threshold="Dose reduction advised in severe renal impairment.",
        hepatic_impairment_guidance="Monitor hepatic enzymes in liver dysfunction.",
        adverse_reactions_common=["Nausea", "Fatigue", "Dizziness", "Headache"],
        adverse_reactions_severe=["Severe hypersensitivity", "Hepatic failure", "Cytopenia"]
    ),
}

INTERACTIONS_ONCOLOGY: Dict[str, DrugInteractionRecord] = {
    "methotrexate_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00636",
        primary_drug="Methotrexate",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00636-R",
        primary_drug="Cyclosporine",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00637",
        primary_drug="Methotrexate",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00637-R",
        primary_drug="Tacrolimus",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00638",
        primary_drug="Methotrexate",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00638-R",
        primary_drug="Azathioprine",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_montelukast": DrugInteractionRecord(
        pair_id="DIP-00639",
        primary_drug="Methotrexate",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00639-R",
        primary_drug="Montelukast",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00640",
        primary_drug="Methotrexate",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00640-R",
        primary_drug="Salbutamol",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00641",
        primary_drug="Methotrexate",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00641-R",
        primary_drug="Fluticasone",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "methotrexate_budesonide": DrugInteractionRecord(
        pair_id="DIP-00642",
        primary_drug="Methotrexate",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Methotrexate and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_methotrexate": DrugInteractionRecord(
        pair_id="DIP-00642-R",
        primary_drug="Budesonide",
        secondary_drug="Methotrexate",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Methotrexate requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00643",
        primary_drug="Cyclosporine",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00643-R",
        primary_drug="Tacrolimus",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00644",
        primary_drug="Cyclosporine",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00644-R",
        primary_drug="Azathioprine",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_montelukast": DrugInteractionRecord(
        pair_id="DIP-00645",
        primary_drug="Cyclosporine",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00645-R",
        primary_drug="Montelukast",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00646",
        primary_drug="Cyclosporine",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00646-R",
        primary_drug="Salbutamol",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00647",
        primary_drug="Cyclosporine",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00647-R",
        primary_drug="Fluticasone",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "cyclosporine_budesonide": DrugInteractionRecord(
        pair_id="DIP-00648",
        primary_drug="Cyclosporine",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Cyclosporine and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_cyclosporine": DrugInteractionRecord(
        pair_id="DIP-00648-R",
        primary_drug="Budesonide",
        secondary_drug="Cyclosporine",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Cyclosporine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00649",
        primary_drug="Tacrolimus",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00649-R",
        primary_drug="Azathioprine",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_montelukast": DrugInteractionRecord(
        pair_id="DIP-00650",
        primary_drug="Tacrolimus",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00650-R",
        primary_drug="Montelukast",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00651",
        primary_drug="Tacrolimus",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00651-R",
        primary_drug="Salbutamol",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00652",
        primary_drug="Tacrolimus",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00652-R",
        primary_drug="Fluticasone",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "tacrolimus_budesonide": DrugInteractionRecord(
        pair_id="DIP-00653",
        primary_drug="Tacrolimus",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Tacrolimus and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_tacrolimus": DrugInteractionRecord(
        pair_id="DIP-00653-R",
        primary_drug="Budesonide",
        secondary_drug="Tacrolimus",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Tacrolimus requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_montelukast": DrugInteractionRecord(
        pair_id="DIP-00654",
        primary_drug="Azathioprine",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00654-R",
        primary_drug="Montelukast",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00655",
        primary_drug="Azathioprine",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00655-R",
        primary_drug="Salbutamol",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00656",
        primary_drug="Azathioprine",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00656-R",
        primary_drug="Fluticasone",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "azathioprine_budesonide": DrugInteractionRecord(
        pair_id="DIP-00657",
        primary_drug="Azathioprine",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Azathioprine and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_azathioprine": DrugInteractionRecord(
        pair_id="DIP-00657-R",
        primary_drug="Budesonide",
        secondary_drug="Azathioprine",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Azathioprine requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00658",
        primary_drug="Montelukast",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_montelukast": DrugInteractionRecord(
        pair_id="DIP-00658-R",
        primary_drug="Salbutamol",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C9,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00659",
        primary_drug="Montelukast",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_montelukast": DrugInteractionRecord(
        pair_id="DIP-00659-R",
        primary_drug="Fluticasone",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2D6,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "montelukast_budesonide": DrugInteractionRecord(
        pair_id="DIP-00660",
        primary_drug="Montelukast",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Montelukast and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_montelukast": DrugInteractionRecord(
        pair_id="DIP-00660-R",
        primary_drug="Budesonide",
        secondary_drug="Montelukast",
        severity=InteractionSeverity.CONTRAINDICATED,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Montelukast requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP3A4,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00661",
        primary_drug="Salbutamol",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00661-R",
        primary_drug="Fluticasone",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MINOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2E1,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "salbutamol_budesonide": DrugInteractionRecord(
        pair_id="DIP-00662",
        primary_drug="Salbutamol",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Salbutamol and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_salbutamol": DrugInteractionRecord(
        pair_id="DIP-00662-R",
        primary_drug="Budesonide",
        secondary_drug="Salbutamol",
        severity=InteractionSeverity.MODERATE,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Salbutamol requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP1A2,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "fluticasone_budesonide": DrugInteractionRecord(
        pair_id="DIP-00663",
        primary_drug="Fluticasone",
        secondary_drug="Budesonide",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Fluticasone and Budesonide requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
    "budesonide_fluticasone": DrugInteractionRecord(
        pair_id="DIP-00663-R",
        primary_drug="Budesonide",
        secondary_drug="Fluticasone",
        severity=InteractionSeverity.MAJOR,
        mechanism_of_action="Competitive enzymatic inhibition and pharmacodynamic receptor synergism.",
        clinical_effect="Alteration in systemic drug concentration and heightened clinical toxicity risk.",
        risk_summary="Co-administration of Budesonide and Fluticasone requires clinical surveillance.",
        management_guidelines="Monitor clinical biomarkers and adjust baseline dosage appropriately.",
        evidence_level=EvidenceLevel.WELL_DOCUMENTED,
        cyp_pathway=CYPEnzyme.CYP2C19,
        onset_timeline="MODERATE",
        monitoring_parameters=["Renal function", "Hepatic transaminases", "Coagulation parameters"]
    ),
}
