# Generated by Django 5.1.15 on 2026-09-03 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('relationship', models.CharField(choices=[('SELF', 'Self (Primary User)'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SPOUSE', 'Spouse'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('OTHER', 'Other Relative/Dependent')], default='OTHER', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=10)),
                ('blood_group', models.CharField(choices=[('A+', 'A Positive (A+)'), ('A-', 'A Negative (A-)'), ('B+', 'B Positive (B+)'), ('B-', 'B Negative (B-)'), ('AB+', 'AB Positive (AB+)'), ('AB-', 'AB Negative (AB-)'), ('O+', 'O Positive (O+)'), ('O-', 'O Negative (O-)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/family/')),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['relationship', 'first_name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='family_fami_user_id_029d3e_idx')],
            },
        ),
    ]
