# Generated by Django 5.1.15 on 2026-09-03 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('activity_type', models.CharField(choices=[('WALKING', 'Walking / Casual Stroll'), ('RUNNING', 'Running / Jogging'), ('CYCLING', 'Cycling / Biking'), ('SWIMMING', 'Swimming'), ('STRENGTH', 'Resistance / Strength Training'), ('YOGA', 'Yoga / Stretching'), ('OTHER', 'Other Physical Exercise')], default='WALKING', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(default=30, help_text='Duration in minutes')),
                ('distance_km', models.FloatField(blank=True, help_text='Distance in kilometers', null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned', null=True)),
                ('steps_count', models.PositiveIntegerField(blank=True, help_text='Pedometer steps', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Activity Record',
                'verbose_name_plural': 'Activity Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('goal_type', models.CharField(choices=[('WEIGHT', 'Target Body Weight (kg)'), ('STEPS', 'Daily Step Count'), ('WATER', 'Daily Hydration Target (ml)'), ('SLEEP', 'Daily Sleep Target (hours)'), ('ADHERENCE', 'Medicine Adherence Target (%)'), ('CUSTOM', 'Custom Wellness Goal')], default='STEPS', max_length=20)),
                ('target_value', models.FloatField(help_text='Target numerical threshold')),
                ('current_value', models.FloatField(default=0.0, help_text='Current progress value')),
                ('unit', models.CharField(default='steps', help_text='e.g. kg, steps, ml, hours, %', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active In Progress'), ('COMPLETED', 'Goal Achieved'), ('PAUSED', 'Paused'), ('FAILED', 'Discontinued / Failed')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Health Goal',
                'verbose_name_plural': 'Health Goals',
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Healthy Snack')], default='BREAKFAST', max_length=20)),
                ('food_items', models.TextField(help_text='Items consumed, e.g. Oatmeal with blueberries, boiled egg')),
                ('calories', models.PositiveIntegerField(blank=True, help_text='Estimated calories (kcal)', null=True)),
                ('water_intake_ml', models.PositiveIntegerField(default=0, help_text='Water consumed with meal (ml)')),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Meal Record',
                'verbose_name_plural': 'Meal Records',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('bedtime', models.TimeField(help_text='Time went to bed, e.g. 23:00')),
                ('wake_time', models.TimeField(help_text='Time woke up, e.g. 07:00')),
                ('duration_hours', models.FloatField(default=8.0, help_text='Total sleep hours')),
                ('sleep_quality', models.CharField(choices=[('POOR', 'Poor (Restless / Fragmented)'), ('FAIR', 'Fair (Moderate rest)'), ('GOOD', 'Good (Restful sleep)'), ('EXCELLENT', 'Excellent (Deep, refreshing sleep)')], default='GOOD', max_length=20)),
                ('interruptions_count', models.PositiveIntegerField(default=0, help_text='Times woken up during night')),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Sleep Record',
                'verbose_name_plural': 'Sleep Records',
                'ordering': ['-date'],
            },
        ),
    ]
