# Generated by Django 5.1.15 on 2026-09-03 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allergen', models.CharField(help_text='e.g. Penicillin, Peanuts, Sulfa drugs', max_length=150)),
                ('allergy_type', models.CharField(choices=[('DRUG', 'Drug / Pharmaceutical'), ('FOOD', 'Food / Dietary'), ('ENVIRONMENTAL', 'Environmental (Dust, Pollen)'), ('INSECT', 'Insect Venom'), ('OTHER', 'Other Substance')], default='DRUG', max_length=20)),
                ('severity', models.CharField(choices=[('MILD', 'Mild (Rash, itching)'), ('MODERATE', 'Moderate (Hives, swelling)'), ('SEVERE', 'Severe (Wheezing, difficulty breathing)'), ('CRITICAL', 'Critical / Anaphylactic Risk')], default='MODERATE', max_length=20)),
                ('reaction', models.CharField(help_text='e.g. Hives, facial swelling, anaphylaxis', max_length=250)),
                ('date_identified', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'ordering': ['-severity', 'allergen'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=150)),
                ('specialization', models.CharField(help_text='e.g. Cardiologist, Pediatrician, General Practitioner', max_length=100)),
                ('hospital_clinic', models.CharField(blank=True, default='', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(default='UNKNOWN', max_length=10)),
                ('height_cm', models.FloatField(blank=True, help_text='Height in centimeters', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight in kilograms', null=True)),
                ('medical_conditions', models.TextField(blank=True, default='', help_text='Chronic illnesses or medical conditions (e.g. Asthma, Hypertension)')),
                ('previous_surgeries', models.TextField(blank=True, default='', help_text='Past surgical procedures and dates')),
                ('family_medical_history', models.TextField(blank=True, default='', help_text='Hereditary or family history')),
                ('important_notes', models.TextField(blank=True, default='')),
                ('family_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Health Profile',
                'verbose_name_plural': 'Health Profiles',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('LAB_REPORT', 'Lab Test / Blood Report'), ('SCAN_REPORT', 'Scan Report (X-Ray, MRI, CT, Ultrasound)'), ('CERTIFICATE', 'Medical Certificate / Fit Certificate'), ('VACCINE', 'Vaccination Card'), ('DOCTOR_REPORT', 'Doctor Discharge / Consultation Summary'), ('OTHER', 'Other Clinical Document')], default='LAB_REPORT', max_length=30)),
                ('file', models.FileField(upload_to='documents/vault/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('document_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Medical Document',
                'verbose_name_plural': 'Medical Documents',
                'ordering': ['-document_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('prescription_date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.TextField(blank=True, default='', help_text='Clinical assessment or diagnosis')),
                ('instructions', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/prescriptions/')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='medical.doctor')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='family.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(help_text='e.g. Twice daily for 5 days', max_length=100)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, default='', max_length=255)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Medicine Item',
                'verbose_name_plural': 'Prescription Medicine Items',
            },
        ),
        migrations.CreateModel(
            name='SymptomRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptom_name', models.CharField(max_length=150)),
                ('severity', models.CharField(choices=[('MILD', 'Mild (Minor discomfort, daily activity unaffected)'), ('MODERATE', 'Moderate (Noticeable discomfort, interferes with tasks)'), ('SEVERE', 'Severe (Incapacitating, seek clinical evaluation)')], default='MILD', max_length=15)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('duration_hours', models.FloatField(blank=True, help_text='Duration in hours', null=True)),
                ('triggers', models.CharField(blank=True, default='', help_text='e.g. Cold weather, Stress, Exercise', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Symptom Record',
                'verbose_name_plural': 'Symptom Records',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_name', models.CharField(max_length=150)),
                ('dose_number', models.CharField(default='1st Dose', max_length=50)),
                ('vaccination_date', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', help_text='Hospital / Health center', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('UPCOMING', 'Upcoming Scheduled'), ('OVERDUE', 'Overdue')], default='COMPLETED', max_length=20)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'ordering': ['-vaccination_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('reason', models.CharField(help_text='e.g. Annual physical, Follow-up consultation', max_length=250)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], db_index=True, default='UPCOMING', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='family.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='medical.doctor')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['date', 'time'],
                'indexes': [models.Index(fields=['family_member', 'date'], name='medical_app_family__cf78ab_idx'), models.Index(fields=['status', 'date'], name='medical_app_status_979f75_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('blood_pressure_systolic', models.PositiveIntegerField(blank=True, help_text='Systolic (mmHg)', null=True)),
                ('blood_pressure_diastolic', models.PositiveIntegerField(blank=True, help_text='Diastolic (mmHg)', null=True)),
                ('blood_sugar_fasting', models.FloatField(blank=True, help_text='Fasting Blood Glucose (mg/dL)', null=True)),
                ('blood_sugar_postprandial', models.FloatField(blank=True, help_text='Postprandial Glucose (mg/dL)', null=True)),
                ('heart_rate', models.PositiveIntegerField(blank=True, help_text='Resting Heart Rate (BPM)', null=True)),
                ('oxygen_saturation', models.FloatField(blank=True, help_text='Blood Oxygen Saturation SpO2 (%)', null=True)),
                ('temperature_c', models.FloatField(blank=True, help_text='Body Temperature (°C)', null=True)),
                ('weight_kg', models.FloatField(blank=True, help_text='Weight (kg)', null=True)),
                ('height_cm', models.FloatField(blank=True, help_text='Height (cm)', null=True)),
                ('bmi', models.FloatField(blank=True, help_text='Computed Body Mass Index', null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='family.familymember')),
            ],
            options={
                'verbose_name': 'Vital Record',
                'verbose_name_plural': 'Vital Records',
                'ordering': ['-date', '-time'],
                'indexes': [models.Index(fields=['family_member', '-date', '-time'], name='medical_vit_family__1fa11f_idx')],
            },
        ),
    ]
