# Generated by Django 5.1.15 on 2026-09-03 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineDose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('scheduled_time', models.TimeField()),
                ('actual_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed / Overdue'), ('DELAYED', 'Taken Late / Delayed'), ('SNOOZED', 'Snoozed')], db_index=True, default='PENDING', max_length=15)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Medicine Dose',
                'verbose_name_plural': 'Medicine Doses',
                'ordering': ['date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Brand or Commercial Name (e.g., Lipitor)', max_length=150)),
                ('generic_name', models.CharField(blank=True, default='', help_text='Active Pharmaceutical Ingredient (e.g., Atorvastatin)', max_length=150)),
                ('brand_name', models.CharField(blank=True, default='', max_length=150)),
                ('medicine_type', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup / Liquid Suspension'), ('INJECTION', 'Injection'), ('CREAM', 'Topical Cream / Ointment'), ('DROPS', 'Drops (Eye / Ear / Nasal)'), ('POWDER', 'Powder / Sachet'), ('INHALER', 'Inhaler / Respules'), ('OTHER', 'Other Formulation')], default='TABLET', max_length=20)),
                ('dosage', models.CharField(help_text='e.g., 1 tablet, 5ml, 2 puffs', max_length=100)),
                ('strength', models.CharField(blank=True, default='', help_text='e.g., 500, 20, 10', max_length=50)),
                ('unit', models.CharField(default='mg', help_text='e.g., mg, mcg, ml, IU', max_length=20)),
                ('instructions', models.CharField(choices=[('BEFORE_FOOD', 'Before Food (30 mins prior)'), ('AFTER_FOOD', 'After Food (with water)'), ('WITH_FOOD', 'With Food / Meal'), ('EMPTY_STOMACH', 'On an Empty Stomach'), ('BEDTIME', 'At Bedtime'), ('AS_NEEDED', 'As Needed (SOS / PRN)')], default='AFTER_FOOD', max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing/chronic regimens', null=True)),
                ('prescribed_by', models.CharField(blank=True, default='', help_text='Doctor or Clinic name', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active Prescribed'), ('INACTIVE', 'Inactive / Paused'), ('COMPLETED', 'Course Completed'), ('DISCONTINUED', 'Discontinued by Doctor')], db_index=True, default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='family.familymember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed / Overdue'), ('DELAYED', 'Taken Late / Delayed'), ('SNOOZED', 'Snoozed')], max_length=20)),
                ('reason_for_skip', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_logs', to='family.familymember')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='medications.medicine')),
                ('dose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='medications.medicinedose')),
            ],
            options={
                'verbose_name': 'Medication Log',
                'verbose_name_plural': 'Medication Logs',
                'ordering': ['-actual_time'],
            },
        ),
        migrations.CreateModel(
            name='MedicineExpiry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, default='LOT-01', max_length=50)),
                ('expiry_date', models.DateField()),
                ('alert_days_before', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('SAFE', 'Safe / Unexpired'), ('EXPIRING_SOON', 'Expiring Soon (<= 30 Days)'), ('EXPIRED', 'Expired - Do Not Use')], db_index=True, default='SAFE', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_batches', to='medications.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Expiry Batch',
                'verbose_name_plural': 'Medicine Expiry Batches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRefill',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refill_date', models.DateField(default=django.utils.timezone.now)),
                ('refill_quantity', models.PositiveIntegerField(default=30)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pharmacy_source', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='medications.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Refill',
                'verbose_name_plural': 'Medicine Refills',
                'ordering': ['-refill_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicineSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency', models.CharField(choices=[('ONCE', 'Once (Single dose)'), ('DAILY', 'Daily (Once a day)'), ('TWICE_DAILY', 'Twice a Day (Morning & Evening)'), ('THREE_TIMES_DAILY', 'Three Times a Day (Morning, Noon, Night)'), ('FOUR_TIMES_DAILY', 'Four Times a Day (Every 6 hours)'), ('WEEKLY', 'Weekly (Specific Day)'), ('AS_NEEDED', 'As Needed (PRN)'), ('CUSTOM', 'Custom Schedule / Selected Days')], default='DAILY', max_length=30)),
                ('specific_times', models.JSONField(default=list, help_text="List of time strings in HH:MM format, e.g., ['08:00', '20:00']")),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of weekday integers (0=Mon, 6=Sun), e.g. [0, 2, 4]')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medications.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Schedule',
                'verbose_name_plural': 'Medicine Schedules',
                'ordering': ['medicine', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicinedose',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medications.medicineschedule'),
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stock', models.IntegerField(default=30)),
                ('initial_quantity', models.IntegerField(default=30)),
                ('consumed_quantity', models.IntegerField(default=0)),
                ('minimum_stock_level', models.IntegerField(default=5, help_text='Alert triggered when stock falls to or below this')),
                ('refill_reminder_days', models.IntegerField(default=7, help_text='Days of supply left before alert')),
                ('unit', models.CharField(default='tablets', max_length=20)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='medications.medicine')),
            ],
            options={
                'verbose_name': 'Medicine Stock',
                'verbose_name_plural': 'Medicine Stocks',
            },
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['user', 'status'], name='medications_user_id_fc92ee_idx'),
        ),
        migrations.AddIndex(
            model_name='medicine',
            index=models.Index(fields=['family_member', 'status'], name='medications_family__c091a3_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['family_member', 'actual_time'], name='medications_family__976817_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationlog',
            index=models.Index(fields=['medicine', 'status'], name='medications_medicin_05daa6_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinedose',
            index=models.Index(fields=['date', 'status'], name='medications_date_510202_idx'),
        ),
        migrations.AddIndex(
            model_name='medicinedose',
            index=models.Index(fields=['schedule', 'date'], name='medications_schedul_cc6bcb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicinedose',
            unique_together={('schedule', 'date', 'scheduled_time')},
        ),
    ]
