# Generated by Django 5.1.15 on 2026-09-03 06:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('CREATE', 'Record Created'), ('UPDATE', 'Record Updated'), ('DELETE', 'Record Deleted'), ('VIEW', 'Sensitive Record Accessed'), ('EXPORT', 'Data Exported'), ('BACKUP', 'System Backup Created'), ('RESTORE', 'System Backup Restored'), ('PASSWORD_CHANGE', 'Password Changed'), ('SETTINGS_CHANGE', 'System Settings Modified')], db_index=True, max_length=30)),
                ('module', models.CharField(choices=[('AUTH', 'Authentication & Access'), ('FAMILY', 'Family Members'), ('MEDICATION', 'Medications & Prescriptions'), ('MEDICAL', 'Medical Records & Clinical Data'), ('WELLNESS', 'Lifestyle & Wellness'), ('ANALYTICS', 'Intelligence & Reports'), ('SYSTEM', 'System Administration'), ('EMERGENCY', 'Emergency & Caregivers')], db_index=True, max_length=30)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('object_id', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('is_security_event', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_audit_module_365bd8_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx')],
            },
        ),
    ]
